.bd B 3
.TH libinfopru 1 "Apr 10, 2014" "TI Tools" "TI Code Generation Tools"
.SH NAME
libinfopru - Library Information Archiver
.SH SYNOPSIS
.B libinfopru
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Builds an archive of information about available libraries.
This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2014, Texas Instruments, Inc.
